version: '3.7'

networks:
  nlpjs:

volumes:
  mongo_data:

services:

  mongo:
    image: mongo:4.0.11
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myadmin
      - MONGO_INITDB_ROOT_PASSWORD=myadmin
      - MONGO_INITDB_DATABASE=nlpjs
      - MONGO_INITDB_USERNAME=nlpjs
      - MONGO_INITDB_PASSWORD=nlpjs
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh    # Init at 1st run
    expose:
      - "27017"
    networks:
      - nlpjs
    healthcheck:
      # it is also possible/valid change the order "mongostat" with the order "mongotop"
      test: ["CMD", "mongostat", "-u", "myadmin", "-p", "myadmin", "--authenticationDatabase=admin", "--json", "-n", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongo-express:
    image: mongo-express:0.49.0
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=myadmin
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=webadmin
      - ME_CONFIG_BASICAUTH_PASSWORD=webadmin
    ports:
      - "8081:8081"
    networks:
      - nlpjs
    depends_on:
      - mongo
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http:///webadmin:webadmin@localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    entrypoint: "/bin/bash -c 'sleep 40s && tini -p SIGTERM -- /docker-entrypoint.sh mongo-express'"

  nlpjs-app:
    build: 
      context: .
      dockerfile: ./docker/nlpjs-app/Dockerfile
    environment:
      - MONGO_URL=mongodb://nlpjs:nlpjs@mongo:27017/nlpjs
      # - SETTINGS_URL=http://localhost:3002
      # - API_URL=http://localhost:3002
      # - PORT=3002
    ports:
      - "3000:3000"
    networks:
      - nlpjs
    stop_signal: SIGTERM
  #   healthcheck:
  #     test: ["CMD", "wget", "--spider", "--quiet", "-T", "2", "-t", "1", "http://localhost:3000"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s
    depends_on:
      - mongo
